import 'package:flutter/widgets.dart';

class AppTexts {
  AppTexts(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'welcomeSubtitle': 'Browse routes, track vehicles, and request trips.',
      'getStarted': 'Get Started',
      'signIn': 'Sign in',
      'profile': 'Profile',
      'fullName': 'Full Name',
      'phone': 'Phone',
      'email': 'Email',
      'save': 'Save',
      'settings': 'Settings',
      'helpSupport': 'Help & Support',
      'logout': 'Log out',
      'profileUpdated': 'Profile updated',
      'driverStatus': 'Driver status',
      'goOnline': 'Go online',
      'goOffline': 'Go offline',
      'onlineQueue': 'You are online and in the driver queue.',
      'offlineQueue': 'You are offline and left the queue.',
      'finishTripHint':
          'Finish your current trip before changing availability.',
      'assignedTripHint':
          'You have an assigned trip. Start it from Trips or wait until the route manager updates the schedule.',
      'changePassword': 'Change Password',
      'takePhoto': 'Take Photo',
      'chooseGallery': 'Choose from Gallery',
      'currentPassword': 'Current Password',
      'newPassword': 'New Password',
      'confirmNewPassword': 'Confirm New Password',
      'cancel': 'Cancel',
      'change': 'Change',
      'passwordChanged': 'Password changed successfully',
      // Auth screens
      'emailAddress': 'Email Address',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'dontHaveAccount': "Don't have an account?",
      'signUp': 'Sign Up',
      'enterEmail': 'Enter your email',
      'enterPassword': 'Enter your password',
      'pleaseEnterEmail': 'Please enter your email',
      'pleaseEnterPassword': 'Please enter your password',
      'phoneNumber': 'Phone Number',
      'enterPhoneNumber': 'Enter your phone number',
      'enterEmailPassword': 'Please enter email and password',
      'loginFailed': 'Login failed',
      'routeManagerLoginSubtitle':
          'Sign in using your route manager email and password.',
      'backToUserLogin': 'Back to user login',
      'sendCode': 'Send Code',
      'pleaseEnterPhone': 'Please enter your phone number',
      'invalidPhone': 'Please enter a valid phone number',
      'rememberMe': 'Remember Me',
      'codeSentTo': 'Code sent to',
      'phoneOtpSubtitle':
          "We'll send you a one-time code (OTP) to verify your number.",
      'enterPhoneNumberSnack': 'Enter a phone number',
      'errorLabel': 'Error',
      'failedToSendOtp': 'Failed to send OTP',
      'otpVerification': 'OTP Verification',
      'enterOtp': 'Enter the code sent to your phone',
      'verify': 'Verify',
      'resendCode': 'Resend Code',
      'didntReceiveCode': "Didn't receive the code?",
      'otpRequired': 'Please enter the OTP code',
      'validSixDigitOtp': 'Enter a valid 6-digit OTP',
      'verificationIdMissing': 'Verification ID is missing.',
      'userNotFoundVerification': 'User not found after verification.',
      'userRoleNotFound': 'User role not found',
      'verificationFailed': 'Verification failed',
      'otpIncorrect': 'The OTP code is incorrect.',
      'otpExpired': 'The OTP code has expired. Please request a new one.',
      'verificationSessionInvalid':
          'Verification session is invalid. Please try again.',
      'resendNotImplemented': 'Resend not implemented yet',
      'verifyPhoneNumber': 'Verify phone number',
      'enterSixDigitCodeSentTo': 'Enter the 6-digit code sent to',
      'didntReceiveSms': "Didn't receive SMS?",
      'continue': 'Continue',
      'otpExpiresNote': 'Note: OTP expires in 2 minutes.',
      'changePhoneNumber': 'Change phone number',
      'firstName': 'First Name',
      'lastName': 'Last Name',
      'confirmPassword': 'Confirm Password',
      'createAccount': 'Create Account',
      'alreadyHaveAccount': 'Already have an account?',
      'pleaseFillAllFields': 'Please fill all fields',
      'phoneAlreadyUsed':
          'This phone number is already used. Please use another number.',
      'couldNotVerifyPhone': 'Could not verify phone number',
      'passengerDetails': 'Passenger details',
      'passengerSignupSubtitle':
          'Enter your full name and phone number to create your account.',
      'exampleFullName': 'e.g. Mohammad Ahmad',
      'agreeTo': 'I agree to',
      'terms': 'Terms',
      'privacy': 'Privacy',
      'pleaseEnterFirstName': 'Please enter your first name',
      'pleaseEnterLastName': 'Please enter your last name',
      'passwordsDoNotMatch': 'Passwords do not match',
      'passwordTooShort': 'Password must be at least 6 characters',
      'selectVehicleType': 'Select Vehicle Type',
      'plateNumber': 'Plate Number',
      'enterPlateNumber': 'Enter plate number',
      'vehicleType': 'Vehicle Type',
      'driverDetails': 'Driver details',
      'selectRoute': 'Select route',
      'routeFromFirestore': 'Route (from Firestore)',
      'couldNotLoadRoutes': 'Could not load routes',
      'noRoutesFound':
          'No routes found. Add documents under collection `route` first.',
      'carNumberPlate': 'Car number (plate)',
      'examplePlateNumber': 'e.g., 7-1234',
      'drivingLicenseOptional': 'Driving license number (optional)',
      'licenseNumberHint': 'License #',
      'carType': 'Car type',
      'selectCarType': 'Select car type',
      'continueToVerifyPhone': 'Continue to verify phone',
      'accountMayRequireApproval': 'Your account may require approval.',
      'required': 'Required',
      'requestReceived': 'Request received',
      'accountPendingApproval':
          "Your account is pending approval.\nWe'll notify you once it's verified.",
      'backToSignIn': 'Back to Sign in',
      'createYourAccount': 'Create Your Account',
      'chooseRoleContinue': 'Choose your role to continue',
      'passengerRole': 'Passenger',
      'passengerRoleDescription': 'Browse routes and request trips',
      'driverRole': 'Driver',
      'driverRoleDescription': 'Accept trips and manage availability',
      'bus': 'Bus',
      'microBus': 'Micro Bus',
      // Nav bars
      'home': 'Home',
      'schedule': 'Schedule',
      'trips': 'Trips',
      'requests': 'Requests',
      // Passenger home
      'hello': 'Hello',
      'whereToGo': 'Where would you like to go?',
      'loadingRoutes': 'Loading routes...',
      'loading': 'Loading...',
      'searchRoute': 'Search or select a route',
      'selectLineFirst': 'Please select a line first',
      'line': 'Line',
      'notSelected': 'Not selected',
      'location': 'Location',
      'now': 'Now',
      'scheduleTrip': 'Schedule a trip',
      'confirmTrip': 'Confirm Trip',
      'numberOfSeats': 'Number of seats',
      'availableDrivers': 'Available Drivers',
      'noDriversAvailable': 'No drivers available for this route right now.',
      'close': 'Close',
      'requestSentTo': 'Request sent to',
      'driverAcceptDecline': 'The driver can accept or decline in Requests.',
      'trackingDriverLive': 'Tracking driver live...',
      'etaToPickup': 'ETA to pickup',
      'stop': 'Stop',
      'myLocation': 'My Location',
      'noVehiclesFound': 'No vehicles found for this line',
      'from': 'From',
      'to': 'To',
      'price': 'Price',
      'availableSeats': 'Available Seats',
      'seats': 'seats',
      'seat': 'seat',
      // Support
      'helpSupportTitle': 'Help & Support',
      'supportSubtitle':
          'Having an issue? Send your complaint to the route manager.',
      'writeComplaint': 'Write your complaint here...',
      'submit': 'Submit',
      'complaintSent': 'Complaint sent to route manager',
      // Trip history
      'tripHistory': 'Trip History',
      'all': 'All',
      'scheduled': 'Scheduled',
      'onTrip': 'On Trip',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'noTripsFound': 'No trips found.',
      'failedToLoadTrips': 'Failed to load trip history.',
      'tripDetails': 'Trip Details',
      'date': 'Date',
      'departure': 'Departure',
      'arrival': 'Arrival',
      'vehicle': 'Vehicle',
      'vehiclePlateNo': 'Vehicle Plate No.',
      'driverPhone': 'Driver Phone',
      'viewRoute': 'View Route',
      'trackLiveTrip': 'Track Live Trip',
      'noDriverAssigned': 'No driver assigned for this trip yet.',
      // Live tracking
      'liveTracking': 'Live tracking',
      'waitingDriverLocation': 'Waiting for driver location…',
      'followingDriver': 'Following driver on the map',
      'driver': 'Driver',
      'liveLocation': 'Live location',
      'you': 'You',
      'yourPickup': 'Your pickup',
      // Notifications
      'notifications': 'Notifications',
      'allNotifications': 'All notifications',
      'searchNotifications': 'Search notifications...',
      'noNotificationsFound': 'No notifications found',
      'failedToLoadNotifications': 'Failed to load notifications',
      'driverApprovalNotificationTitle': 'Driver request accepted',
      'driverApprovalNotificationMessage':
          'Your driver account has been approved. You can now start accepting trips.',
      // Driver home
      'liveTripInProgress': 'Live trip in progress',
      'noActiveTrip': 'No active trip',
      'youAreOffline': 'You are Offline',
      'youHaveAssignedTrip': 'You have an Assigned trip',
      'youAreAvailable': 'You are Available',
      'assignedTrips': 'Assigned trips',
      'available': 'Available',
      'assigned': 'Assigned',
      'offline': 'Offline',
      'activeTrip': 'Active Trip',
      'endTrip': 'End Trip',
      'tripEndedSuccess': 'Trip ended successfully',
      'failedEndTrip': 'Failed to end trip',
      'total': 'Total',
      'onMap': 'On Map',
      'capacity': 'Capacity',
      'eta': 'ETA',
      'passenger': 'Passenger',
      // Driver trips
      'failedToLoadTripsDriver': 'Failed to load trips.',
      'bookedSeats': 'Booked Seats',
      'time': 'Time',
      // Driver requests
      'tripRequests': 'Trip Requests',
      'searchRequests': 'Search requests...',
      'signInToSeeRequests': 'Sign in to see requests.',
      'couldNotLoadRequests': 'Could not load requests.',
      'noPendingRequests': 'No pending requests',
      'noRequestsMatch': 'No requests match your search',
      'requestAccepted': 'Request accepted',
      'requestDeclined': 'Request declined',
      'decline': 'Decline',
      'accept': 'Accept',
      'pickup': 'Pickup',
      // Trip details (driver)
      'reviewBeforeStarting': 'Review before starting',
      'failedToLoadTripDetails': 'Failed to load trip details.',
      'tripNotFound': 'Trip not found.',
      'tripIdLabel': 'Trip ID',
      'passengers': 'Passengers',
      'noPassengersAssigned': 'No passengers assigned.',
      'startTrip': 'Start Trip',
      'cancelTrip': 'Cancel Trip',
      'cancelTripConfirm':
          'Are you sure you want to cancel this trip? This action cannot be undone.',
      'no': 'No',
      'yesCancelTrip': 'Yes, Cancel',
      'tripIdMissing': 'Trip ID is missing',
      'tripCancelledSuccess': 'Trip cancelled successfully',
      'failedToCancel': 'Failed to cancel',
      'canStartBefore': 'You can start this trip 30 minutes before departure.',
      'startingSharesLocation':
          'Starting the trip will share your live location',
      'couldNotStart': 'Could not start',
      // Route manager
      'routeManager': 'Route Manager',
      'routeSchedule': 'Route schedule',
      'addTrip': 'Add trip',
      'assign1': 'Assign 1',
      'driverQueue': 'Driver queue',
      'clearQueue': 'Clear queue',
      'queueAllAvailable': 'Queue all available',
      'queueEmpty': 'Queue is empty.',
      'availableDriversAppend': 'Available drivers — tap to append',
      'noAvailableDrivers': 'No available drivers',
      'noTripsForType': 'No trips for this vehicle type',
      'deleteTrip': 'Delete trip',
      'removeTripConfirm': 'Remove this trip from the schedule?',
      'delete': 'Delete',
      'tripRemoved': 'Trip removed',
      'tripUpdated': 'Trip updated',
      'unassigned': 'Unassigned',
      // Assign driver
      'assignments': 'Assignments',
      'driverStatusSubtitle':
          'Queue is automatic (online + available). New trips are assigned FIFO.',
      'driversOnRoute':
          'Drivers on your route (status from drivers collection)',
      'noDriversForRoute': 'No drivers for this route.',
      'noRouteLinkedAccount':
          'No route linked to this account. Set routeId on users or route_manager.',
      'noVehicle': 'No vehicle',
      'queuePosition': 'Queue position',
      'notInQueue': 'Not in queue',
      'assignToTrip': 'Assign to trip',
      'driverAssigned': 'Driver assigned to scheduled trip.',
      'assignmentFailed': 'Assignment failed',
      'noUpcomingTrips': 'No upcoming scheduled trips on this route.',
      'assign': 'Assign',
      // Reports
      'reports': 'Reports',
      'reportsSubtitle': 'Review and forward passenger and driver reports',
      'searchReports': 'Search reports...',
      'failedToLoadReports': 'Failed to load reports',
      'noReportsYet': 'No reports yet',
      'sendToAdmin': 'Send to Admin',
      'noReportsSelected': 'No reports selected!',
      'reportsSentSuccess': 'Reports sent to admin successfully!',
      'reportDetails': 'Report details',
      'message': 'Message',
      'status': 'Status',
      'role': 'Role',
      'route': 'Route',
      // Add schedule slot
      'editTrip': 'Edit trip',
      'scheduleATrip': 'Schedule a trip',
      'saveChanges': 'Save changes',
      'saveTrip': 'Save trip',
      'selectDateAndTime': 'Please choose date and time',
      'selectEndTime': 'Please choose end time / last departure',
      'selectCapacity': 'Please select capacity',
      'invalidPrice': 'Invalid price',
      'startTripTime': 'Start trip time',
      'capacitySeats': 'Capacity (seats)',
      'priceOverride': 'Price override (optional)',
      'leaveEmptyRouteDefault': 'Leave empty to use route default',
      'repeatEvery': 'Repeat every (minutes, optional)',
      'leaveEmptySingleTrip': 'Leave empty for a single trip',
      'tripLengthMinutes': 'Trip length (minutes)',
      'firstDeparture': 'First departure',
      'lastDeparture': 'Last departure (start time)',
      // Notification compose
      'sendNotification': 'Send notification',
      'messageDrivers': 'Message drivers on your route',
      'writeNotificationMsg': 'Write the notification message...',
      'receivers': 'Receivers',
      'allDrivers': 'All drivers',
      'specific': 'Specific',
      'noDriversOnRoute': 'No drivers are assigned to this route.',
      'sending': 'Sending...',
      // Schedule screen (passenger)
      'searchSchedule': 'Schedule Ride',
      'vehicleTypeLabel': 'Vehicle Type',
      'selectDate': 'Select date',
      'selectTime': 'Select time',
      'search': 'Search',
      'pickupLocation': 'Pickup Location',
      'enterPickup': 'Enter pickup location',
      'bookTrip': 'Book Trip',
      'noSchedulesFound': 'No schedules found',
      'bookingSuccess': 'Trip booked successfully!',
      'alreadyBooked': 'Already booked',
      'availableTrips': 'Available Trips',
      'anyDate': 'Any date',
      'anyTime': 'Any time',
      'allLines': 'All lines',
      'dateAndTime': 'Date & Time',
      'pickupHint':
          'Defaults to the point selected on the home map. You can edit the text (e.g. street or landmark).',
      'confirmSchedule': 'Confirm schedule',
      'scheduleConfirmed': 'Schedule confirmed for',
      'seatsAvailableForTrip': 'seat(s) are available for this trip.',
      'setPickupFirst':
          'Set your pickup on the home map (tap the map or use My Location), then try again.',
      'joinWaitingList': 'Join waiting list',
      'waitingTripRequested': 'Waiting request submitted.',
      'waitingTripCreated':
          'A new trip was created for your requested date and time.',
      'waitingTripManagerNotified':
          'Waiting request submitted. The route manager was notified.',
      'waitingListChooseDateTime':
          'Choose a date and time to join the waiting list.',
      'waitingListLoginRequired': 'Please sign in to join the waiting list.',
      'waitingListSelectSeat': 'Please select at least 1 seat.',
      'waitingListFutureDateTime': 'Please choose a future date and time.',
      'waitingListRouteNotFound': 'Route not found for this line.',
      'waitingTripCreatedTitle': 'New trip created',
      'waitingTripCreatedMessage':
          'A new trip was created for your requested date and time.',
      'waitingTripManagerTitle': 'Waiting list trip request',
      'waitingTripManagerMessage':
          'Passengers are waiting for a trip at the requested date and time.',
      'createTrip': 'Create trip',
      'makeTrip': 'Make trip',
      'waitingTripMade': 'Trip created and assigned successfully.',
      'waitingListManagerPrompt':
          'You have trip on waiting list for {passengers} passengers on {date} at {time}. If you want to make it.',
      'waitingList': 'Waiting list',
      'waitingListSubtitle': 'Passenger requests ready for your decision',
      'noWaitingListRequests': 'No waiting list requests yet.',
      'requestedPassengers': 'Requested passengers',
      'noWaitingPassengerRequests': 'No passenger requests found.',
      'seatsRequested': 'Seats requested',
      // Add schedule slot - extra
      'select': 'Select',
      'chooseDateAndTime': 'Please choose date and time',
      'chooseEndTime': 'Please choose end time / last departure',
      'enterTripLength': 'Enter trip length in minutes (e.g. 60)',
      'endTimeAfterStart': 'End time must be after start time',
      'checkDepartureTimes': 'Check departure times for repeating bus trips',
      'savedTrips': 'Saved',
      'tripsLabel': 'trips',
      'noDriversQueue': 'No drivers in queue — assign manually.',
      'tripSaved': 'Trip saved.',
      'autoAssigned': 'auto-assigned',
      'withoutQueueDriver': 'without queue driver',
      'driversAssignedQueue': 'Drivers assigned from queue.',
      'driverAssignedQueue': 'Driver assigned from queue.',
      'couldNotSave': 'Could not save',
      'microSubtitle': 'Start time, date, and capacity',
      'busRepeatSubtitle':
          'First departure, last departure start, trip length, repeat interval',
      'busSubtitle': 'Departure window, date, and capacity',
      'leaveEmptySingle': 'Leave empty for a single trip',
      'leaveEmptyDefault': 'Leave empty to use route default',
      'unknownUser': 'Unknown user',
    },
    'ar': {
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'welcomeSubtitle': 'تصفح المسارات، تتبع المركبات، واطلب الرحلات.',
      'getStarted': 'ابدأ الآن',
      'signIn': 'تسجيل الدخول',
      'profile': 'الملف الشخصي',
      'fullName': 'الاسم الكامل',
      'phone': 'الهاتف',
      'email': 'البريد الإلكتروني',
      'save': 'حفظ',
      'settings': 'الإعدادات',
      'helpSupport': 'المساعدة والدعم',
      'logout': 'تسجيل الخروج',
      'profileUpdated': 'تم تحديث الملف الشخصي',
      'driverStatus': 'حالة السائق',
      'goOnline': 'اتصال',
      'goOffline': 'غير متصل',
      'onlineQueue': 'أنت متصل الآن وفي قائمة السائقين.',
      'offlineQueue': 'أنت غير متصل الآن وتمت إزالتك من القائمة.',
      'finishTripHint': 'أكمل رحلتك الحالية قبل تغيير حالة التوفر.',
      'assignedTripHint':
          'لديك رحلة مخصصة. ابدأها من صفحة الرحلات أو انتظر تحديث مدير المسار.',
      'changePassword': 'تغيير كلمة المرور',
      'takePhoto': 'التقاط صورة',
      'chooseGallery': 'اختيار من المعرض',
      'currentPassword': 'كلمة المرور الحالية',
      'newPassword': 'كلمة المرور الجديدة',
      'confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
      'cancel': 'إلغاء',
      'change': 'تغيير',
      'passwordChanged': 'تم تغيير كلمة المرور بنجاح',
      'emailAddress': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'signUp': 'إنشاء حساب',
      'enterEmail': 'أدخل بريدك الإلكتروني',
      'enterPassword': 'أدخل كلمة المرور',
      'pleaseEnterEmail': 'يرجى إدخال البريد الإلكتروني',
      'pleaseEnterPassword': 'يرجى إدخال كلمة المرور',
      'phoneNumber': 'رقم الهاتف',
      'enterPhoneNumber': 'أدخل رقم هاتفك',
      'enterEmailPassword': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
      'loginFailed': 'فشل تسجيل الدخول',
      'routeManagerLoginSubtitle':
          'سجّل الدخول باستخدام بريد وكلمة مرور مدير المسار.',
      'backToUserLogin': 'العودة إلى تسجيل دخول المستخدم',
      'sendCode': 'إرسال الرمز',
      'pleaseEnterPhone': 'يرجى إدخال رقم الهاتف',
      'invalidPhone': 'يرجى إدخال رقم هاتف صحيح',
      'rememberMe': 'تذكرني',
      'codeSentTo': 'تم إرسال الرمز إلى',
      'phoneOtpSubtitle': 'سنرسل لك رمزاً لمرة واحدة (OTP) للتحقق من رقمك.',
      'enterPhoneNumberSnack': 'أدخل رقم الهاتف',
      'errorLabel': 'خطأ',
      'failedToSendOtp': 'فشل إرسال رمز التحقق',
      'otpVerification': 'التحقق من الرمز',
      'enterOtp': 'أدخل الرمز المرسل إلى هاتفك',
      'verify': 'تحقق',
      'resendCode': 'إعادة إرسال الرمز',
      'didntReceiveCode': 'لم تستلم الرمز؟',
      'otpRequired': 'يرجى إدخال رمز التحقق',
      'validSixDigitOtp': 'أدخل رمز تحقق صحيحاً من 6 أرقام',
      'verificationIdMissing': 'معرّف التحقق مفقود.',
      'userNotFoundVerification': 'لم يتم العثور على المستخدم بعد التحقق.',
      'userRoleNotFound': 'لم يتم العثور على دور المستخدم',
      'verificationFailed': 'فشل التحقق',
      'otpIncorrect': 'رمز التحقق غير صحيح.',
      'otpExpired': 'انتهت صلاحية رمز التحقق. يرجى طلب رمز جديد.',
      'verificationSessionInvalid':
          'جلسة التحقق غير صالحة. يرجى المحاولة مرة أخرى.',
      'resendNotImplemented': 'إعادة الإرسال غير متاحة حالياً',
      'verifyPhoneNumber': 'تحقق من رقم الهاتف',
      'enterSixDigitCodeSentTo': 'أدخل الرمز المكوّن من 6 أرقام المرسل إلى',
      'didntReceiveSms': 'لم تصلك الرسالة؟',
      'continue': 'متابعة',
      'otpExpiresNote': 'ملاحظة: تنتهي صلاحية الرمز خلال دقيقتين.',
      'changePhoneNumber': 'تغيير رقم الهاتف',
      'firstName': 'الاسم الأول',
      'lastName': 'اسم العائلة',
      'confirmPassword': 'تأكيد كلمة المرور',
      'createAccount': 'إنشاء حساب',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'pleaseFillAllFields': 'يرجى تعبئة جميع الحقول',
      'phoneAlreadyUsed': 'رقم الهاتف مستخدم بالفعل. يرجى استخدام رقم آخر.',
      'couldNotVerifyPhone': 'تعذر التحقق من رقم الهاتف',
      'passengerDetails': 'بيانات الراكب',
      'passengerSignupSubtitle': 'أدخل اسمك الكامل ورقم هاتفك لإنشاء حسابك.',
      'exampleFullName': 'مثال: محمد أحمد',
      'agreeTo': 'أوافق على',
      'terms': 'الشروط',
      'privacy': 'الخصوصية',
      'pleaseEnterFirstName': 'يرجى إدخال الاسم الأول',
      'pleaseEnterLastName': 'يرجى إدخال اسم العائلة',
      'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
      'passwordTooShort': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'selectVehicleType': 'اختر نوع المركبة',
      'plateNumber': 'رقم اللوحة',
      'enterPlateNumber': 'أدخل رقم اللوحة',
      'vehicleType': 'نوع المركبة',
      'driverDetails': 'بيانات السائق',
      'selectRoute': 'اختر المسار',
      'routeFromFirestore': 'المسار (من Firestore)',
      'couldNotLoadRoutes': 'تعذر تحميل المسارات',
      'noRoutesFound': 'لا توجد مسارات. أضف مستندات داخل مجموعة `route` أولاً.',
      'carNumberPlate': 'رقم المركبة (اللوحة)',
      'examplePlateNumber': 'مثال: 7-1234',
      'drivingLicenseOptional': 'رقم رخصة القيادة (اختياري)',
      'licenseNumberHint': 'رقم الرخصة',
      'carType': 'نوع المركبة',
      'selectCarType': 'اختر نوع المركبة',
      'continueToVerifyPhone': 'متابعة للتحقق من الهاتف',
      'accountMayRequireApproval': 'قد يحتاج حسابك إلى موافقة.',
      'required': 'مطلوب',
      'requestReceived': 'تم استلام الطلب',
      'accountPendingApproval':
          'حسابك بانتظار الموافقة.\nسنبلغك عند التحقق منه.',
      'backToSignIn': 'العودة إلى تسجيل الدخول',
      'createYourAccount': 'إنشاء حسابك',
      'chooseRoleContinue': 'اختر دورك للمتابعة',
      'passengerRole': 'راكب',
      'passengerRoleDescription': 'تصفح المسارات واطلب الرحلات',
      'driverRole': 'سائق',
      'driverRoleDescription': 'اقبل الرحلات وأدر حالة التوفر',
      'bus': 'حافلة',
      'microBus': 'حافلة صغيرة',
      'home': 'الرئيسية',
      'schedule': 'الجدول',
      'trips': 'الرحلات',
      'requests': 'الطلبات',
      'hello': 'مرحباً',
      'whereToGo': 'إلى أين تريد الذهاب؟',
      'loadingRoutes': 'جاري تحميل المسارات...',
      'loading': 'جاري التحميل...',
      'searchRoute': 'ابحث أو اختر مساراً',
      'selectLineFirst': 'يرجى اختيار خط أولاً',
      'line': 'الخط',
      'notSelected': 'غير محدد',
      'location': 'الموقع',
      'now': 'الآن',
      'scheduleTrip': 'جدولة رحلة',
      'confirmTrip': 'تأكيد الرحلة',
      'numberOfSeats': 'عدد المقاعد',
      'availableDrivers': 'السائقون المتاحون',
      'noDriversAvailable': 'لا يوجد سائقون متاحون لهذا المسار حالياً.',
      'close': 'إغلاق',
      'requestSentTo': 'تم إرسال الطلب إلى',
      'driverAcceptDecline': 'يمكن للسائق القبول أو الرفض من الطلبات.',
      'trackingDriverLive': 'تتبع السائق مباشرة...',
      'etaToPickup': 'الوقت المتوقع للوصول',
      'stop': 'إيقاف',
      'myLocation': 'موقعي',
      'noVehiclesFound': 'لا توجد مركبات لهذا الخط',
      'from': 'من',
      'to': 'إلى',
      'price': 'السعر',
      'availableSeats': 'المقاعد المتاحة',
      'seats': 'مقاعد',
      'seat': 'مقعد',
      'helpSupportTitle': 'المساعدة والدعم',
      'supportSubtitle': 'هل لديك مشكلة؟ أرسل شكواك إلى مدير المسار.',
      'writeComplaint': 'اكتب شكواك هنا...',
      'submit': 'إرسال',
      'complaintSent': 'تم إرسال الشكوى إلى مدير المسار',
      'tripHistory': 'سجل الرحلات',
      'all': 'الكل',
      'scheduled': 'مجدولة',
      'onTrip': 'في رحلة',
      'completed': 'مكتملة',
      'cancelled': 'ملغية',
      'noTripsFound': 'لا توجد رحلات.',
      'failedToLoadTrips': 'فشل تحميل سجل الرحلات.',
      'tripDetails': 'تفاصيل الرحلة',
      'date': 'التاريخ',
      'departure': 'المغادرة',
      'arrival': 'الوصول',
      'vehicle': 'المركبة',
      'vehiclePlateNo': 'رقم لوحة المركبة',
      'driverPhone': 'هاتف السائق',
      'viewRoute': 'عرض المسار',
      'trackLiveTrip': 'تتبع الرحلة مباشرة',
      'noDriverAssigned': 'لم يتم تعيين سائق لهذه الرحلة بعد.',
      'liveTracking': 'التتبع المباشر',
      'waitingDriverLocation': 'في انتظار موقع السائق…',
      'followingDriver': 'متابعة السائق على الخريطة',
      'driver': 'السائق',
      'liveLocation': 'الموقع المباشر',
      'you': 'أنت',
      'yourPickup': 'نقطة الالتقاط',
      'notifications': 'الإشعارات',
      'allNotifications': 'جميع الإشعارات',
      'searchNotifications': 'البحث في الإشعارات...',
      'noNotificationsFound': 'لا توجد إشعارات',
      'failedToLoadNotifications': 'فشل تحميل الإشعارات',
      'driverApprovalNotificationTitle': 'تم قبول طلب السائق',
      'driverApprovalNotificationMessage':
          'تمت الموافقة على حساب السائق الخاص بك. يمكنك الآن قبول الرحلات.',
      'liveTripInProgress': 'رحلة مباشرة قيد التنفيذ',
      'noActiveTrip': 'لا توجد رحلة نشطة',
      'youAreOffline': 'أنت غير متصل',
      'youHaveAssignedTrip': 'لديك رحلة مخصصة',
      'youAreAvailable': 'أنت متاح',
      'assignedTrips': 'الرحلات المخصصة',
      'available': 'متاح',
      'assigned': 'مخصص',
      'offline': 'غير متصل',
      'activeTrip': 'رحلة نشطة',
      'endTrip': 'إنهاء الرحلة',
      'tripEndedSuccess': 'تم إنهاء الرحلة بنجاح',
      'failedEndTrip': 'فشل إنهاء الرحلة',
      'total': 'الإجمالي',
      'onMap': 'على الخريطة',
      'capacity': 'السعة',
      'eta': 'الوقت المتوقع للوصول',
      'passenger': 'راكب',
      'failedToLoadTripsDriver': 'فشل تحميل الرحلات.',
      'bookedSeats': 'المقاعد المحجوزة',
      'time': 'الوقت',
      'tripRequests': 'طلبات الرحلات',
      'searchRequests': 'البحث في الطلبات...',
      'signInToSeeRequests': 'سجل الدخول لرؤية الطلبات.',
      'couldNotLoadRequests': 'تعذر تحميل الطلبات.',
      'noPendingRequests': 'لا توجد طلبات معلقة',
      'noRequestsMatch': 'لا توجد طلبات مطابقة',
      'requestAccepted': 'تم قبول الطلب',
      'requestDeclined': 'تم رفض الطلب',
      'decline': 'رفض',
      'accept': 'قبول',
      'pickup': 'نقطة الالتقاط',
      'reviewBeforeStarting': 'مراجعة قبل البدء',
      'failedToLoadTripDetails': 'فشل تحميل تفاصيل الرحلة.',
      'tripNotFound': 'الرحلة غير موجودة.',
      'tripIdLabel': 'معرف الرحلة',
      'passengers': 'الركاب',
      'noPassengersAssigned': 'لا يوجد ركاب معينون.',
      'startTrip': 'بدء الرحلة',
      'cancelTrip': 'إلغاء الرحلة',
      'cancelTripConfirm':
          'هل أنت متأكد من إلغاء هذه الرحلة؟ لا يمكن التراجع عن هذا الإجراء.',
      'no': 'لا',
      'yesCancelTrip': 'نعم، إلغاء',
      'tripIdMissing': 'معرف الرحلة مفقود',
      'tripCancelledSuccess': 'تم إلغاء الرحلة بنجاح',
      'failedToCancel': 'فشل الإلغاء',
      'canStartBefore': 'يمكنك بدء هذه الرحلة قبل 30 دقيقة من المغادرة.',
      'startingSharesLocation': 'بدء الرحلة سيشارك موقعك المباشر',
      'couldNotStart': 'تعذر البدء',
      'routeManager': 'مدير المسار',
      'routeSchedule': 'جدول المسار',
      'addTrip': 'إضافة رحلة',
      'assign1': 'تعيين 1',
      'driverQueue': 'قائمة السائقين',
      'clearQueue': 'مسح القائمة',
      'queueAllAvailable': 'إضافة جميع المتاحين',
      'queueEmpty': 'القائمة فارغة.',
      'availableDriversAppend': 'السائقون المتاحون — اضغط للإضافة',
      'noAvailableDrivers': 'لا يوجد سائقون متاحون',
      'noTripsForType': 'لا توجد رحلات لنوع المركبة هذا',
      'deleteTrip': 'حذف الرحلة',
      'removeTripConfirm': 'هل تريد إزالة هذه الرحلة من الجدول؟',
      'delete': 'حذف',
      'tripRemoved': 'تمت إزالة الرحلة',
      'tripUpdated': 'تم تحديث الرحلة',
      'unassigned': 'غير معين',
      'assignments': 'التعيينات',
      'driverStatusSubtitle':
          'القائمة تلقائية (متصل + متاح). يتم تعيين الرحلات الجديدة حسب ترتيب القائمة.',
      'driversOnRoute': 'السائقون على مسارك (الحالة من مجموعة السائقين)',
      'noDriversForRoute': 'لا يوجد سائقون لهذا المسار.',
      'noRouteLinkedAccount':
          'لا يوجد مسار مرتبط بهذا الحساب. عيّن routeId في users أو route_manager.',
      'noVehicle': 'لا توجد مركبة',
      'queuePosition': 'ترتيب القائمة',
      'notInQueue': 'ليس في القائمة',
      'assignToTrip': 'تعيين لرحلة',
      'driverAssigned': 'تم تعيين السائق لرحلة مجدولة.',
      'assignmentFailed': 'فشل التعيين',
      'noUpcomingTrips': 'لا توجد رحلات مجدولة قادمة على هذا المسار.',
      'assign': 'تعيين',
      'reports': 'التقارير',
      'reportsSubtitle': 'مراجعة وإعادة توجيه تقارير الركاب والسائقين',
      'searchReports': 'البحث في التقارير...',
      'failedToLoadReports': 'فشل تحميل التقارير',
      'noReportsYet': 'لا توجد تقارير بعد',
      'sendToAdmin': 'إرسال للمسؤول',
      'noReportsSelected': 'لم يتم اختيار تقارير!',
      'reportsSentSuccess': 'تم إرسال التقارير للمسؤول بنجاح!',
      'reportDetails': 'تفاصيل التقرير',
      'message': 'الرسالة',
      'status': 'الحالة',
      'role': 'الدور',
      'route': 'المسار',
      'editTrip': 'تعديل الرحلة',
      'scheduleATrip': 'جدولة رحلة',
      'saveChanges': 'حفظ التغييرات',
      'saveTrip': 'حفظ الرحلة',
      'selectDateAndTime': 'يرجى اختيار التاريخ والوقت',
      'selectEndTime': 'يرجى اختيار وقت النهاية / آخر مغادرة',
      'selectCapacity': 'يرجى اختيار السعة',
      'invalidPrice': 'سعر غير صالح',
      'startTripTime': 'وقت بدء الرحلة',
      'capacitySeats': 'السعة (مقاعد)',
      'priceOverride': 'تعديل السعر (اختياري)',
      'leaveEmptyRouteDefault': 'اتركه فارغاً لاستخدام السعر الافتراضي',
      'repeatEvery': 'تكرار كل (دقائق، اختياري)',
      'leaveEmptySingleTrip': 'اتركه فارغاً لرحلة واحدة',
      'tripLengthMinutes': 'مدة الرحلة (دقائق)',
      'firstDeparture': 'أول مغادرة',
      'lastDeparture': 'آخر مغادرة (وقت البدء)',
      'sendNotification': 'إرسال إشعار',
      'messageDrivers': 'إرسال رسالة للسائقين على مسارك',
      'writeNotificationMsg': 'اكتب رسالة الإشعار...',
      'receivers': 'المستلمون',
      'allDrivers': 'جميع السائقين',
      'specific': 'محدد',
      'noDriversOnRoute': 'لا يوجد سائقون معينون لهذا المسار.',
      'sending': 'جاري الإرسال...',
      'searchSchedule': 'حجز رحلة مجدولة',
      'vehicleTypeLabel': 'نوع المركبة',
      'selectDate': 'اختر التاريخ',
      'selectTime': 'اختر الوقت',
      'search': 'بحث',
      'pickupLocation': 'موقع الالتقاط',
      'enterPickup': 'أدخل موقع الالتقاط',
      'bookTrip': 'حجز الرحلة',
      'noSchedulesFound': 'لا توجد جداول',
      'bookingSuccess': 'تم حجز الرحلة بنجاح!',
      'alreadyBooked': 'محجوز مسبقاً',
      'availableTrips': 'الرحلات المتاحة',
      'anyDate': 'أي تاريخ',
      'anyTime': 'أي وقت',
      'allLines': 'جميع الخطوط',
      'dateAndTime': 'التاريخ والوقت',
      'pickupHint':
          'يعتمد على النقطة المحددة على الخريطة الرئيسية. يمكنك تعديل النص (مثل الشارع أو المعلم).',
      'confirmSchedule': 'تأكيد الجدول',
      'scheduleConfirmed': 'تم تأكيد الجدول لـ',
      'seatsAvailableForTrip': 'مقعد(مقاعد) متاحة لهذه الرحلة.',
      'setPickupFirst':
          'حدد موقع الالتقاط على الخريطة الرئيسية (انقر على الخريطة أو استخدم موقعي)، ثم حاول مرة أخرى.',
      'joinWaitingList': 'انضم إلى قائمة الانتظار',
      'waitingTripRequested': 'تم إرسال طلب قائمة الانتظار.',
      'waitingTripCreated': 'تم إنشاء رحلة جديدة في التاريخ والوقت المطلوبين.',
      'waitingTripManagerNotified':
          'تم إرسال طلب قائمة الانتظار. تم إشعار مدير المسار.',
      'waitingListChooseDateTime':
          'اختر التاريخ والوقت للانضمام إلى قائمة الانتظار.',
      'waitingListLoginRequired':
          'يرجى تسجيل الدخول للانضمام إلى قائمة الانتظار.',
      'waitingListSelectSeat': 'يرجى اختيار مقعد واحد على الأقل.',
      'waitingListFutureDateTime': 'يرجى اختيار تاريخ ووقت في المستقبل.',
      'waitingListRouteNotFound': 'لم يتم العثور على المسار لهذا الخط.',
      'waitingTripCreatedTitle': 'تم إنشاء رحلة جديدة',
      'waitingTripCreatedMessage':
          'تم إنشاء رحلة جديدة في التاريخ والوقت المطلوبين.',
      'waitingTripManagerTitle': 'طلب رحلة من قائمة الانتظار',
      'waitingTripManagerMessage':
          'يوجد ركاب بانتظار رحلة في التاريخ والوقت المطلوبين.',
      'createTrip': 'إنشاء رحلة',
      'makeTrip': 'إنشاء الرحلة',
      'waitingTripMade': 'تم إنشاء الرحلة وتعيينها بنجاح.',
      'waitingListManagerPrompt':
          'لديك رحلة في قائمة الانتظار لعدد {passengers} ركاب بتاريخ {date} الساعة {time}. إذا كنت تريد إنشاءها.',
      'waitingList': 'قائمة الانتظار',
      'waitingListSubtitle': 'طلبات الركاب الجاهزة لقرارك',
      'noWaitingListRequests': 'لا توجد طلبات في قائمة الانتظار بعد.',
      'requestedPassengers': 'الركاب الذين طلبوا الرحلة',
      'noWaitingPassengerRequests': 'لا توجد طلبات ركاب.',
      'seatsRequested': 'المقاعد المطلوبة',
      'select': 'اختر',
      'chooseDateAndTime': 'يرجى اختيار التاريخ والوقت',
      'chooseEndTime': 'يرجى اختيار وقت النهاية / آخر مغادرة',
      'enterTripLength': 'أدخل مدة الرحلة بالدقائق (مثال: 60)',
      'endTimeAfterStart': 'وقت النهاية يجب أن يكون بعد وقت البداية',
      'checkDepartureTimes': 'تحقق من أوقات المغادرة للرحلات المتكررة',
      'savedTrips': 'تم حفظ',
      'tripsLabel': 'رحلات',
      'noDriversQueue': 'لا يوجد سائقون في الطابور — عيّن يدوياً.',
      'tripSaved': 'تم حفظ الرحلة.',
      'autoAssigned': 'تم تعيينهم تلقائياً',
      'withoutQueueDriver': 'بدون سائق من الطابور',
      'driversAssignedQueue': 'تم تعيين السائقين من الطابور.',
      'driverAssignedQueue': 'تم تعيين السائق من الطابور.',
      'couldNotSave': 'تعذر الحفظ',
      'microSubtitle': 'وقت البداية، التاريخ، والسعة',
      'busRepeatSubtitle': 'أول مغادرة، آخر مغادرة، مدة الرحلة، فاصل التكرار',
      'busSubtitle': 'نافذة المغادرة، التاريخ، والسعة',
      'leaveEmptySingle': 'اتركه فارغاً لرحلة واحدة',
      'leaveEmptyDefault': 'اتركه فارغاً لاستخدام الافتراضي',
      'unknownUser': 'مستخدم مجهول',
    },
  };

  String t(String key) {
    final lang = _strings[locale.languageCode] ?? _strings['en']!;
    return lang[key] ?? _strings['en']![key] ?? key;
  }
}
