// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZ7y1NxNDTf5_SGBy7cKprbosW7_TERk',
    appId: '1:1085605678072:web:133a92b59c858c735f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    authDomain: 'navigo-c89a0.firebaseapp.com',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    measurementId: 'G-SY2VMBYQ6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYq1-adwyvioIvSHrmCVVZ8IOwh5wiPso',
    appId: '1:1085605678072:android:7cb1f54261033b635f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36tzEGJK8mFyIwH75ZBORvJMVbuJI9cM',
    appId: '1:1085605678072:ios:ba6c1dbbc22585325f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36tzEGJK8mFyIwH75ZBORvJMVbuJI9cM',
    appId: '1:1085605678072:ios:ba6c1dbbc22585325f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArZ7y1NxNDTf5_SGBy7cKprbosW7_TERk',
    appId: '1:1085605678072:web:133a92b59c858c735f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    authDomain: 'navigo-c89a0.firebaseapp.com',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    measurementId: 'G-SY2VMBYQ6R',
  );

}
