// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZ7y1NxNDTf5_SGBy7cKprbosW7_TERk',
    appId: '1:1085605678072:web:ad6a33607bc263555f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    authDomain: 'navigo-c89a0.firebaseapp.com',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    measurementId: 'G-EZCKHRZKY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYq1-adwyvioIvSHrmCVVZ8IOwh5wiPso',
    appId: '1:1085605678072:android:64ad1aa5eed918ad5f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36tzEGJK8mFyIwH75ZBORvJMVbuJI9cM',
    appId: '1:1085605678072:ios:980567764eed54cf5f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    iosBundleId: 'com.example.navigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36tzEGJK8mFyIwH75ZBORvJMVbuJI9cM',
    appId: '1:1085605678072:ios:980567764eed54cf5f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    iosBundleId: 'com.example.navigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArZ7y1NxNDTf5_SGBy7cKprbosW7_TERk',
    appId: '1:1085605678072:web:c06dc00e6c91264f5f640d',
    messagingSenderId: '1085605678072',
    projectId: 'navigo-c89a0',
    authDomain: 'navigo-c89a0.firebaseapp.com',
    storageBucket: 'navigo-c89a0.firebasestorage.app',
    measurementId: 'G-LZ72859DEN',
  );
}
