import 'package:flutter/widgets.dart';

class AdminTexts {
  AdminTexts(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'adminLogin': 'Admin Login',
      'signInToContinue': 'Sign in to continue',
      'email': 'Email',
      'password': 'Password',
      'rememberMe': 'Remember me',
      'login': 'Login',
      'loginFailed': 'Login Failed',
      'adminPanelCouldNotStart': 'Admin panel could not start',
      'checkFirebaseConfiguration':
          'Check Firebase configuration for the platform you are running.',
      'navigoAdmin': 'Navigo Admin',
      'systemControlPanel': 'System Control Panel',
      'dashboard': 'Dashboard',
      'drivers': 'Drivers',
      'routes': 'Routes',
      'routeManagers': 'Route Managers',
      'trips': 'Trips',
      'passengers': 'Passengers',
      'reports': 'Reports',
      'admin': 'Admin',
      'changePassword': 'Change password',
      'show': 'Show',
      'hide': 'Hide',
      'logout': 'Logout',
      'loggingOut': 'Logging out...',
      'loggedOutSuccessfully': 'Logged out successfully',
      'welcomeBackAdmin':
          "Welcome back, Admin! Here's what's happening with your system.",
      'totalUsers': 'Total Users',
      'allUsers': 'All users',
      'activeRoutes': 'Active Routes',
      'availableRoutes': 'Available routes',
      'activeTrips': 'Active Trips',
      'onGoing': 'On going',
      'pendingReview': 'pending review',
      'driversApproval': 'Drivers Approval',
      'reviewAndApproveDrivers': 'Review and approve drivers',
      'tripsManagement': 'Trips Management',
      'manageAllTrips': 'Manage all trips',
      'routesManagement': 'Routes Management',
      'manageAllRoutes': 'Manage all routes',
      'reportsAnalytics': 'Reports & Analytics',
      'adminReports': 'admin reports',
      'systemOverview': 'System Overview',
      'approvedDrivers': 'Approved Drivers',
      'pendingDrivers': 'Pending Drivers',
      'passengersUsers': 'Passengers / Users',
      'pendingApprovals': 'Pending Approvals',
      'noPendingApprovals': 'No pending approvals',
      'type': 'Type',
      'name': 'Name',
      'details': 'Details',
      'status': 'Status',
      'action': 'Action',
      'approve': 'Approve',
      'reject': 'Reject',
      'errorLoadingDashboard': 'Error loading dashboard',
      'couldNotUpdateDriver': 'Could not update driver',
      'approved': 'approved',
      'rejected': 'rejected',
      'adminAccount': 'Admin Account',
      'close': 'Close',
      'currentPassword': 'Current password',
      'newPassword': 'New password',
      'confirmNewPassword': 'Confirm new password',
      'confirmPassword': 'Confirm password',
      'cancel': 'Cancel',
      'changePasswordButton': 'Change Password',
      'noLoggedInAdmin': 'No logged in admin account found.',
      'fillAllPasswordFields': 'Please fill all password fields.',
      'passwordMinLength': 'New password must be at least 6 characters.',
      'passwordsDoNotMatch': 'New passwords do not match.',
      'passwordChangedSuccessfully': 'Password changed successfully',
      'currentPasswordIncorrect': 'Current password is incorrect.',
      'newPasswordWeak': 'New password is too weak.',
      'loginAgainChangePassword':
          'Please log in again before changing the password.',
      'searchDrivers': 'Search drivers...',
      'searchRoutes': 'Search routes...',
      'searchRouteManagers': 'Search route managers...',
      'searchTrips': 'Search trips...',
      'searchPassengers': 'Search passengers...',
      'searchReports': 'Search reports...',
      'driversSubtitle':
          'All drivers with information from users and drivers collections',
      'routesSubtitle': 'All routes from the route collection',
      'routeManagersSubtitle':
          'All route managers with information from users and route_manger collections',
      'tripsSubtitle': 'Schedule slots from each route document',
      'passengersSubtitle':
          'All passengers with information from users and passengers collections',
      'reportsSentToAdmin': 'Reports Sent To Admin',
      'reportsSentSubtitle':
          'Reports sent by route managers from supportReports',
      'errorLoadingDrivers': 'Error loading drivers',
      'errorLoadingRoutes': 'Error loading routes',
      'errorLoadingRouteManagers': 'Error loading route managers',
      'errorLoadingTrips': 'Error loading trips',
      'errorLoadingPassengers': 'Error loading passengers',
      'errorLoadingReports': 'Error loading reports',
      'noDriversFound': 'No drivers found',
      'noRoutesFound': 'No routes found',
      'noRouteManagersFound': 'No route managers found',
      'noTripsFoundForRoute': 'No trips found for this route',
      'noPassengersFound': 'No passengers found',
      'noReportsSent': 'No reports sent to admin yet',
      'phone': 'Phone',
      'approval': 'Approval',
      'vehicle': 'Vehicle',
      'route': 'Route',
      'open': 'Open',
      'online': 'Online',
      'offline': 'Offline',
      'yes': 'Yes',
      'no': 'No',
      'routeId': 'Route ID',
      'start': 'Start',
      'end': 'End',
      'price': 'Price',
      'vehicles': 'Vehicles',
      'slots': 'Slots',
      'driverQueue': 'Driver Queue',
      'updated': 'Updated',
      'createRoute': 'Create Route',
      'createRouteManager': 'Create Route Manager',
      'verified': 'Verified',
      'actions': 'Actions',
      'allRoutes': 'All Routes',
      'filterByRoute': 'Filter by route',
      'departure': 'Departure',
      'arrival': 'Arrival',
      'driver': 'Driver',
      'seats': 'Seats',
      'booked': 'booked',
      'left': 'left',
      'reportDetails': 'Report Details',
      'reportInformation': 'Report Information',
      'createdAt': 'Created At',
      'sentToAdminAt': 'Sent To Admin At',
      'senderAndRoute': 'Sender And Route',
      'sender': 'Sender',
      'senderRole': 'Sender Role',
      'message': 'Message',
      'pickup': 'Pickup',
      'lastLocation': 'Last Location',
      'routeCreated': 'Route created',
      'routeManagerCreated': 'Route manager created',
      'routeManagerUpdated': 'Route manager updated',
      'accountInformation': 'Account Information',
      'driverId': 'Driver ID',
      'userId': 'User ID',
      'managerId': 'Manager ID',
      'passengerId': 'Passenger ID',
      'driverStatus': 'Driver Status',
      'approvalStatus': 'Approval Status',
      'routeAndVehicle': 'Route And Vehicle',
      'routeAssignment': 'Route Assignment',
      'vehicleId': 'Vehicle ID',
      'vehicleType': 'Vehicle Type',
      'plateNumber': 'Plate Number',
      'licenseNumber': 'License Number',
      'dates': 'Dates',
      'updatedAt': 'Updated At',
      'location': 'Location',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'lastUpdate': 'Last Update',
      'startPoint': 'Start point',
      'endPoint': 'End point',
      'startPointRequired': 'Start point is required',
      'endPointRequired': 'End point is required',
      'pickStartEndLocations': 'Pick start and end locations from the map',
      'pickStartLocation': 'Pick start location from the map',
      'pickEndLocation': 'Pick end location from the map',
      'selected': 'Selected',
      'enterValidPrice': 'Enter a valid price',
      'vehicleTypes': 'Vehicle types',
      'addVehicleType': 'Add at least one vehicle type',
      'routeLocations': 'Route locations',
      'zoomIn': 'Zoom in',
      'zoomOut': 'Zoom out',
      'setStartOnMap': 'Click the map to set the start location.',
      'setEndOnMap': 'Click the map to set the end location.',
      'searchLocation': 'Search location',
      'searchLocationHint': 'Search country, city, district, or address',
      'locationNotFound': 'Location not found. Try a more specific address.',
      'locationSearchFailed': 'Could not search for this location.',
      'creating': 'Creating...',
      'couldNotCreateRoute': 'Could not create route',
      'editRouteManager': 'Edit Route Manager',
      'edit': 'Edit',
      'firstName': 'First name',
      'lastName': 'Last name',
      'code': 'Code',
      'phoneNumber': 'Phone number',
      'nineDigits': '9 digits',
      'phoneRule':
          'Phone must start with +970 or +972 and contain exactly 9 digits after it.',
      'passwordRules':
          'Password rules: at least 8 characters, with uppercase, lowercase, number, and special character.',
      'loadingRoutes': 'Loading routes...',
      'selectRoute': 'Select a route',
      'saving': 'Saving...',
      'saveChanges': 'Save Changes',
      'nameRequired': '{label} is required',
      'nameLettersOnly': '{label} can contain letters only',
      'emailRequired': 'Email is required',
      'validEmail': 'Enter a valid email',
      'phoneRequired': 'Phone number is required',
      'phoneNineNumbers': 'Enter exactly 9 numbers',
      'emailAlreadyExists': 'Email is already in the database',
      'phoneAlreadyExists': 'Phone number is already in the database',
      'passwordEight': 'Use at least 8 characters',
      'passwordUppercase': 'Add an uppercase letter',
      'passwordLowercase': 'Add a lowercase letter',
      'passwordNumber': 'Add a number',
      'passwordSpecial': 'Add a special character',
      'noDate': 'No date',
      'tripStatusScheduled': 'Scheduled',
      'tripStatusOngoing': 'Ongoing',
      'tripStatusActive': 'Active',
      'tripStatusStarted': 'Started',
      'tripStatusCompleted': 'Completed',
      'tripStatusCancelled': 'Cancelled',
      'tripStatusPending': 'Pending',
      'tripStatusAssigned': 'Assigned',
      'tripStatusUnassigned': 'Unassigned',
    },
    'ar': {
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'adminLogin': 'تسجيل دخول المسؤول',
      'signInToContinue': 'سجل الدخول للمتابعة',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'rememberMe': 'تذكرني',
      'login': 'تسجيل الدخول',
      'loginFailed': 'فشل تسجيل الدخول',
      'adminPanelCouldNotStart': 'تعذر تشغيل لوحة المسؤول',
      'checkFirebaseConfiguration':
          'تحقق من إعدادات Firebase للمنصة التي تعمل عليها.',
      'navigoAdmin': 'مسؤول Navigo',
      'systemControlPanel': 'لوحة التحكم بالنظام',
      'dashboard': 'لوحة التحكم',
      'drivers': 'السائقون',
      'routes': 'المسارات',
      'routeManagers': 'مديرو المسارات',
      'trips': 'الرحلات',
      'passengers': 'الركاب',
      'reports': 'التقارير',
      'admin': 'المسؤول',
      'changePassword': 'تغيير كلمة المرور',
      'show': 'إظهار',
      'hide': 'إخفاء',
      'logout': 'تسجيل الخروج',
      'loggingOut': 'جار تسجيل الخروج...',
      'loggedOutSuccessfully': 'تم تسجيل الخروج بنجاح',
      'welcomeBackAdmin': 'مرحباً بك، هذه آخر مستجدات النظام.',
      'totalUsers': 'إجمالي المستخدمين',
      'allUsers': 'كل المستخدمين',
      'activeRoutes': 'المسارات النشطة',
      'availableRoutes': 'المسارات المتاحة',
      'activeTrips': 'الرحلات النشطة',
      'onGoing': 'قيد التنفيذ',
      'pendingReview': 'بانتظار المراجعة',
      'driversApproval': 'موافقة السائقين',
      'reviewAndApproveDrivers': 'راجع طلبات السائقين ووافق عليها',
      'tripsManagement': 'إدارة الرحلات',
      'manageAllTrips': 'إدارة كل الرحلات',
      'routesManagement': 'إدارة المسارات',
      'manageAllRoutes': 'إدارة كل المسارات',
      'reportsAnalytics': 'التقارير والتحليلات',
      'adminReports': 'تقارير المسؤول',
      'systemOverview': 'نظرة عامة على النظام',
      'approvedDrivers': 'السائقون المعتمدون',
      'pendingDrivers': 'السائقون قيد المراجعة',
      'passengersUsers': 'الركاب / المستخدمون',
      'pendingApprovals': 'طلبات الموافقة المعلقة',
      'noPendingApprovals': 'لا توجد طلبات موافقة معلقة',
      'type': 'النوع',
      'name': 'الاسم',
      'details': 'التفاصيل',
      'status': 'الحالة',
      'action': 'الإجراء',
      'approve': 'موافقة',
      'reject': 'رفض',
      'errorLoadingDashboard': 'خطأ في تحميل لوحة التحكم',
      'couldNotUpdateDriver': 'تعذر تحديث السائق',
      'approved': 'تمت الموافقة عليه',
      'rejected': 'تم رفضه',
      'adminAccount': 'حساب المسؤول',
      'close': 'إغلاق',
      'currentPassword': 'كلمة المرور الحالية',
      'newPassword': 'كلمة المرور الجديدة',
      'confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
      'confirmPassword': 'تأكيد كلمة المرور',
      'cancel': 'إلغاء',
      'changePasswordButton': 'تغيير كلمة المرور',
      'noLoggedInAdmin': 'لا يوجد حساب مسؤول مسجل الدخول.',
      'fillAllPasswordFields': 'يرجى تعبئة كل حقول كلمة المرور.',
      'passwordMinLength': 'كلمة المرور الجديدة يجب أن تكون 6 أحرف على الأقل.',
      'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين.',
      'passwordChangedSuccessfully': 'تم تغيير كلمة المرور بنجاح',
      'currentPasswordIncorrect': 'كلمة المرور الحالية غير صحيحة.',
      'newPasswordWeak': 'كلمة المرور الجديدة ضعيفة.',
      'loginAgainChangePassword':
          'يرجى تسجيل الدخول مرة أخرى قبل تغيير كلمة المرور.',
      'searchDrivers': 'البحث في السائقين...',
      'searchRoutes': 'البحث في المسارات...',
      'searchRouteManagers': 'البحث في مديري المسارات...',
      'searchTrips': 'البحث في الرحلات...',
      'searchPassengers': 'البحث في الركاب...',
      'searchReports': 'البحث في التقارير...',
      'driversSubtitle':
          'كل السائقين مع معلوماتهم من مجموعتي المستخدمين والسائقين',
      'routesSubtitle': 'كل المسارات من مجموعة route',
      'routeManagersSubtitle':
          'كل مديري المسارات مع معلوماتهم من مجموعتي المستخدمين ومديري المسارات',
      'tripsSubtitle': 'مواعيد الرحلات من كل مستند مسار',
      'passengersSubtitle':
          'كل الركاب مع معلوماتهم من مجموعتي المستخدمين والركاب',
      'reportsSentToAdmin': 'التقارير المرسلة إلى المسؤول',
      'reportsSentSubtitle':
          'التقارير المرسلة من مديري المسارات من supportReports',
      'errorLoadingDrivers': 'خطأ في تحميل السائقين',
      'errorLoadingRoutes': 'خطأ في تحميل المسارات',
      'errorLoadingRouteManagers': 'خطأ في تحميل مديري المسارات',
      'errorLoadingTrips': 'خطأ في تحميل الرحلات',
      'errorLoadingPassengers': 'خطأ في تحميل الركاب',
      'errorLoadingReports': 'خطأ في تحميل التقارير',
      'noDriversFound': 'لم يتم العثور على سائقين',
      'noRoutesFound': 'لم يتم العثور على مسارات',
      'noRouteManagersFound': 'لم يتم العثور على مديري مسارات',
      'noTripsFoundForRoute': 'لا توجد رحلات لهذا المسار',
      'noPassengersFound': 'لم يتم العثور على ركاب',
      'noReportsSent': 'لا توجد تقارير مرسلة إلى المسؤول بعد',
      'phone': 'الهاتف',
      'approval': 'الموافقة',
      'vehicle': 'المركبة',
      'route': 'المسار',
      'open': 'فتح',
      'online': 'متصل',
      'offline': 'غير متصل',
      'yes': 'نعم',
      'no': 'لا',
      'routeId': 'معرف المسار',
      'start': 'البداية',
      'end': 'النهاية',
      'price': 'السعر',
      'vehicles': 'المركبات',
      'slots': 'المواعيد',
      'driverQueue': 'قائمة السائقين',
      'updated': 'آخر تحديث',
      'createRoute': 'إنشاء مسار',
      'createRouteManager': 'إنشاء مدير مسار',
      'verified': 'موثق',
      'actions': 'الإجراءات',
      'allRoutes': 'كل المسارات',
      'filterByRoute': 'تصفية حسب المسار',
      'departure': 'المغادرة',
      'arrival': 'الوصول',
      'driver': 'السائق',
      'seats': 'المقاعد',
      'booked': 'محجوز',
      'left': 'متبقي',
      'reportDetails': 'تفاصيل التقرير',
      'reportInformation': 'معلومات التقرير',
      'createdAt': 'وقت الإنشاء',
      'sentToAdminAt': 'وقت الإرسال إلى المسؤول',
      'senderAndRoute': 'المرسل والمسار',
      'sender': 'المرسل',
      'senderRole': 'دور المرسل',
      'message': 'الرسالة',
      'pickup': 'نقطة الالتقاط',
      'lastLocation': 'آخر موقع',
      'routeCreated': 'تم إنشاء المسار',
      'routeManagerCreated': 'تم إنشاء مدير المسار',
      'routeManagerUpdated': 'تم تحديث مدير المسار',
      'accountInformation': 'معلومات الحساب',
      'driverId': 'معرف السائق',
      'userId': 'معرف المستخدم',
      'managerId': 'معرف المدير',
      'passengerId': 'معرف الراكب',
      'driverStatus': 'حالة السائق',
      'approvalStatus': 'حالة الموافقة',
      'routeAndVehicle': 'المسار والمركبة',
      'routeAssignment': 'تعيين المسار',
      'vehicleId': 'معرف المركبة',
      'vehicleType': 'نوع المركبة',
      'plateNumber': 'رقم اللوحة',
      'licenseNumber': 'رقم الرخصة',
      'dates': 'التواريخ',
      'updatedAt': 'وقت التحديث',
      'location': 'الموقع',
      'latitude': 'خط العرض',
      'longitude': 'خط الطول',
      'lastUpdate': 'آخر تحديث',
      'startPoint': 'نقطة البداية',
      'endPoint': 'نقطة النهاية',
      'startPointRequired': 'نقطة البداية مطلوبة',
      'endPointRequired': 'نقطة النهاية مطلوبة',
      'pickStartEndLocations': 'اختر نقطتي البداية والنهاية من الخريطة',
      'pickStartLocation': 'اختر نقطة البداية من الخريطة',
      'pickEndLocation': 'اختر نقطة النهاية من الخريطة',
      'selected': 'المحدد',
      'enterValidPrice': 'أدخل سعراً صالحاً',
      'vehicleTypes': 'أنواع المركبات',
      'addVehicleType': 'أضف نوع مركبة واحداً على الأقل',
      'routeLocations': 'مواقع المسار',
      'zoomIn': 'تكبير',
      'zoomOut': 'تصغير',
      'setStartOnMap': 'انقر على الخريطة لتحديد نقطة البداية.',
      'setEndOnMap': 'انقر على الخريطة لتحديد نقطة النهاية.',
      'searchLocation': 'البحث عن موقع',
      'searchLocationHint': 'ابحث عن دولة أو مدينة أو حي أو عنوان',
      'locationNotFound': 'لم يتم العثور على الموقع. جرّب عنواناً أكثر تحديداً.',
      'locationSearchFailed': 'تعذر البحث عن هذا الموقع.',
      'creating': 'جار الإنشاء...',
      'couldNotCreateRoute': 'تعذر إنشاء المسار',
      'editRouteManager': 'تعديل مدير المسار',
      'edit': 'تعديل',
      'firstName': 'الاسم الأول',
      'lastName': 'اسم العائلة',
      'code': 'الرمز',
      'phoneNumber': 'رقم الهاتف',
      'nineDigits': '9 أرقام',
      'phoneRule':
          'يجب أن يبدأ الهاتف بـ +970 أو +972 وأن يحتوي على 9 أرقام بعده بالضبط.',
      'passwordRules':
          'قواعد كلمة المرور: 8 أحرف على الأقل، مع حرف كبير وحرف صغير ورقم ورمز خاص.',
      'loadingRoutes': 'جار تحميل المسارات...',
      'selectRoute': 'اختر مساراً',
      'saving': 'جار الحفظ...',
      'saveChanges': 'حفظ التغييرات',
      'nameRequired': '{label} مطلوب',
      'nameLettersOnly': '{label} يمكن أن يحتوي على أحرف فقط',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'validEmail': 'أدخل بريداً إلكترونياً صالحاً',
      'phoneRequired': 'رقم الهاتف مطلوب',
      'phoneNineNumbers': 'أدخل 9 أرقام بالضبط',
      'emailAlreadyExists': 'البريد الإلكتروني موجود مسبقاً في قاعدة البيانات',
      'phoneAlreadyExists': 'رقم الهاتف موجود مسبقاً في قاعدة البيانات',
      'passwordEight': 'استخدم 8 أحرف على الأقل',
      'passwordUppercase': 'أضف حرفاً كبيراً',
      'passwordLowercase': 'أضف حرفاً صغيراً',
      'passwordNumber': 'أضف رقماً',
      'passwordSpecial': 'أضف رمزاً خاصاً',
      'noDate': 'لا يوجد تاريخ',
      'tripStatusScheduled': 'مجدولة',
      'tripStatusOngoing': 'قيد التنفيذ',
      'tripStatusActive': 'نشطة',
      'tripStatusStarted': 'بدأت',
      'tripStatusCompleted': 'مكتملة',
      'tripStatusCancelled': 'ملغاة',
      'tripStatusPending': 'معلقة',
      'tripStatusAssigned': 'معينة',
      'tripStatusUnassigned': 'غير معينة',
    },
  };

  String t(String key) {
    final lang = _strings[locale.languageCode] ?? _strings['en']!;
    return lang[key] ?? _strings['en']![key] ?? key;
  }
}
